---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
install:
  # molecule version >v2.22 required for compatibility with ansible 2.8.x (provided in the used docker image)
  - pip install molecule==2.22
  - pip install docker
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
