---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: centos-7
    image: fiercely/centos7:systemd
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
